# Generated by Django 5.1.4 on 2025-01-03 01:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(default='easy', max_length=10)),
                ('gameState', models.CharField(default='opening', max_length=50)),
                ('board', models.JSONField(default=list)),
            ],
        ),
    ]
