# Generated by Django 5.1.4 on 2024-12-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_game_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dificulty',
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(default='easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default=list),
        ),
    ]
